import type { EntityType } from "../document.js";

/** LevelMap.entities[] 接受的稳定身份。 */
export const MapEntityTypeId = {
  BOBBY: "bobby",

  WATER: "water",
  ORIGINAL_TILE: "original-tile",
  WATERFALL: "waterfall",
  STARFIELD: "starfield",
  MOON: "moon",
  SNOW_CLOUD: "snow-cloud",
  GRASS: "grass",
  FENCE: "fence",
  HEDGE: "hedge",
  TREE: "tree",
  STONE_WALL: "stone-wall",
  STUMP: "stump",
  FLOWER_POT: "flower-pot",
  ROCK: "rock",
  MUSHROOM: "mushroom",
  SNOWMAN: "snowman",
  CANDY_CANE: "candy-cane",
  CHRISTMAS_TREE: "christmas-tree",
  SNOW_FENCE: "snow-fence",
  SNOWY_ROCK: "snowy-rock",
  CACTUS: "cactus",
  SAND: "sand",
  TRANSPARENT: "transparent",
  CLOUD_PARKING: "cloud-parking",

  START: "start",
  ICE: "ice",
  EXIT: "exit",
  SHOP_DREAM_MACHINE_TICKET: "shop-dream-machine-ticket",
  SHOP_CLOUD9_TICKET: "shop-cloud9-ticket",
  LOCK_KEY: "lock-key",
  SHOP_STEREO_SYSTEM: "shop-stereo-system",
  SHOP_EXTRA_MUSIC: "shop-extra-music",
  SHOP_SPEED_SHOES: "shop-speed-shoes",
  SHOP_COIN_RADAR: "shop-coin-radar",
  SHOP_EMPTY: "shop-empty",
  SHOVEL_PICKUP: "shovel-pickup",
  MOWER_PARKING: "mower-parking",
  TIDE: "tide",
  TIDE_SWITCH: "tide-switch",
  SPEED_SWITCH: "speed-switch",
  CAROUSEL_SWITCH: "carousel-switch",
  WIND_SWITCH: "wind-switch",
  TRAP: "trap",
  MIRROR: "mirror",
  SPEED: "speed",
  CAROUSEL: "carousel",
  COLOR_SWITCH: "color-switch",
  COLOR_BLOCK: "color-block",
  HIGH_GRASS: "high-grass",
  SNOW: "snow",
  CARROT: "carrot",
  EGG: "egg",
  LOCK: "lock",
  BEANSTALK: "beanstalk",
  BEAN: "bean",
  WINDMILL: "windmill",
  PLANK: "plank",
  DRAGON: "dragon",
  SANDMAN: "sandman",
  DREAM_MACHINE: "dream-machine",
  MOWER: "mower",
  GAS: "gas",
  BEAN_FIELD: "bean-field",
  CLOUD: "cloud",
  ICE_BLOCK: "ice-block",
  BEAVER: "beaver",
  LEAF: "leaf",
  CRUMBLY_ROCK: "crumbly-rock",
  PUSHABLE_BOX: "pushable-box",
  KITE: "kite",
  WHIRLWIND: "whirlwind",
  LANDING: "landing",
  GOLDEN_CARROT: "golden-carrot",
  BONUS_COIN: "bonus-coin",
  PORTAL: "portal",
  PUSH_GOAL: "push-goal",
} as const satisfies Record<string, EntityType>;

export type NamedMapEntityType =
  (typeof MapEntityTypeId)[keyof typeof MapEntityTypeId];

/** LevelMap 中可持久化的 canonical Entity 身份。 */
export type MapEntityType = NamedMapEntityType;
