import type { EntityType } from "../document.js";

/**
 * 当前 Engine/original adapter 实现使用的过渡 ID。
 * 其中一部分属于 Runtime/presentation phase，不进入稳定 Map ABI。
 * Engine 与 adapter 全部直接消费 canonical Map Entity 合同后即可删除此模块。
 */
export const EntityTypeId = {
  BOBBY: "bobby",
  SNOW: "snow",
  WATER: "water",
  START: "start",
  SHOVEL_CLEARED_GROUND: "shovel-cleared-ground",
  ICE: "ice",
  EXIT: "exit",
  SHOP_DREAM_MACHINE_TICKET: "shop-dream-machine-ticket",
  SHOP_CLOUD9_TICKET: "shop-cloud9-ticket",
  SHOP_SUPER_KEY: "shop-super-key",
  SHOP_STEREO_SYSTEM: "shop-stereo-system",
  SHOP_EXTRA_MUSIC: "shop-extra-music",
  SHOP_SPEED_SHOES: "shop-speed-shoes",
  SHOP_COIN_RADAR: "shop-coin-radar",
  SHOP_EMPTY: "shop-empty",
  SHOVEL_PICKUP: "shovel-pickup",
  MOWER_PARKING: "mower-parking",
  TIDE: "tide",
  TIDE_SWITCH: "tide-switch",
  SPEED_SWITCH: "speed-switch",
  CAROUSEL_SWITCH: "carousel-switch",
  WIND_SWITCH: "wind-switch",
  TRAP: "trap",
  MIRROR: "mirror",
  SPEED: "speed",
  CAROUSEL: "carousel",
  COLOR_SWITCH: "color-switch",
  COLOR_BLOCK: "color-block",
  HIGH_GRASS: "high-grass",
  HIGH_GRASS_OBJECTIVE: "high-grass-objective",
  CONSUMED_CARROT: "consumed-carrot",
  CARROT: "carrot",
  EGG_EMPTY: "egg-empty",
  EGG_FILLED: "egg-filled",
  LOCK: "lock",
  BEANSTALK_TIP: "beanstalk-tip",
  BEAN: "bean",
  WINDMILL_UP: "windmill-up",
  WINDMILL_DOWN: "windmill-down",
  WINDMILL_LEFT: "windmill-left",
  WINDMILL_RIGHT: "windmill-right",
  PLANK: "plank",
  PLANK_CRUMBLING: "plank-crumbling",
  PLANK_FRAGMENT: "plank-fragment",
  DRAGON: "dragon",
  FIREBALL: "fireball",
  SANDMAN: "sandman",
  DREAM_MACHINE: "dream-machine",
  MOWER: "mower",
  GAS: "gas",
  BEANSTALK_MID: "beanstalk-mid",
  BEAN_FIELD: "bean-field",
  CLOUD: "cloud",
  ICE_BLOCK: "ice-block",
  BEAVER: "beaver",
  LEAF: "leaf",
  CRUMBLY_ROCK: "crumbly-rock",
  BEANSTALK_BASE: "beanstalk-base",
  BEAN_SPROUT: "bean-sprout",
  CLOUD_PARKING: "cloud-parking",
  KITE: "kite",
  WHIRLWIND: "whirlwind",
  LANDING: "landing",
  GOLDEN_CARROT: "golden-carrot",
  BONUS_COIN: "bonus-coin",
  FENCE: "fence",
  PORTAL: "portal",
  PUSH_GOAL: "push-goal",
} as const satisfies Record<string, EntityType>;
