export { createBlankLevel, fromLevelMap, toLevelMap, cloneEditorLevel, normalizeEditorLevel, resizeEditorLevel } from "./level/editorLevel.js";
export { serializeEditorLevel, parseEditorLevel } from "./level/serialization.js";
export { validateEditorLevel } from "./level/validation.js";
export type { EditorMap, EditorLevel, EntityRef, InspectedEditorEntity, LevelValidationIssue } from "./level/types.js";
export { builtinEditorDefinition, EDITOR_DIRECTIONS, applyEditorVariant } from "./definitions/builtin.js";
export type { EditorTool, EditorPlacementPreset, EditorSelection, EditorClipboard, EditorPlacementPoint, EditorEntityVariant, EditorQuickAction, EditorEntityDefinition, EditorPalettePreview, EditorPaletteEntry, EditorPaletteGroup, EditorPaletteDefinition, EditorDeletionCandidate, EditorDeleteContext, EditorDeletionDefinition, EditorValidationContext, EditorMapValidator, EditorDefinition } from "./definitions/types.js";
export { EditorDocument } from "./document/EditorDocument.js";
export type { EditorSnapshot, EditorDocumentListener } from "./document/EditorDocument.js";
export { addEntity, addEntities, removeEntity, removeEntities, moveEntity, replaceEntity, setEntityDirection, updateEntityProperties, updateEntityState, updateEntityTraits, updateMetadata, resizeDocument, updateWinCondition, updateMaxMoves, updateMaxTimeSeconds } from "./document/commands.js";
export type { EditorCommand } from "./document/commands.js";
export { EditorPreview } from "./authoring/EditorPreview.js";
export type { EditorCellInspection, EditorPresenceInspection } from "./authoring/EditorPreview.js";
export { entityCells, placeEntity, resolvePlacement, topEntityRefAt } from "./authoring/entityPlacement.js";
export type { Cell, EntityPlacementPlan, PlacementCell, PlacementOverrides } from "./authoring/entityPlacement.js";
export { resolveEditorPalette, paletteItems, paletteGroups, paletteGroup, paletteLabel } from "./authoring/paletteCatalog.js";
export type { PaletteItem, ResolvedPaletteGroup } from "./authoring/paletteCatalog.js";
export { resolveDeletionTarget } from "./authoring/deletion.js";
export { selectionRect, selectedEntityRefs } from "./authoring/selection.js";
export type { SelectionRect } from "./authoring/selection.js";
export { copySelection, pasteClipboard } from "./authoring/clipboard.js";
export { buildInspectorModel } from "./authoring/inspectorModel.js";
export type { InspectorModel, InspectorEntityModel } from "./authoring/inspectorModel.js";
export { EditorViewport } from "./canvas/EditorViewport.js";
export type { EditorViewportState } from "./canvas/EditorViewport.js";
export { EditorCanvasRenderer, EDITOR_TILE_SIZE } from "./canvas/EditorCanvasRenderer.js";
export type { EditorCanvasRenderState } from "./canvas/EditorCanvasRenderer.js";
export { EditorCanvasInput } from "./canvas/EditorCanvasInput.js";
export type { EditorCanvasInputHandlers, EditorCanvasContextMenuRequest } from "./canvas/EditorCanvasInput.js";
export { canvasPointToCell } from "./canvas/coordinates.js";
export { createBuiltinEntityCatalog } from "@bobby/engine";
export type { EntityCatalog, EntityCatalogEntry, EntityFieldDefinition } from "@bobby/engine";
