import { ObjectId, Terrain, type LevelMap, type ObjectType, type TerrainType } from '@bobby/model';
import { collapseObjectLayouts, isObjectLayoutPart, objectLayoutFor } from '@bobby/engine';

export interface EditorLevel extends LevelMap { schemaVersion:2; name:string; author?:string; description?:string; objects:EditorObject[]; }
export interface EditorObject { type:ObjectType; x:number; y:number; }
export interface LevelValidationIssue { level:'error'|'warning'; message:string; }

export function createBlankLevel(width=16,height=16):EditorLevel {const safeWidth=clampDimension(width),safeHeight=clampDimension(height);const terrain=Array.from({length:safeHeight},()=>Array.from({length:safeWidth},()=>Terrain.GROUND_C as TerrainType));terrain[Math.min(2,safeHeight-1)]![Math.min(2,safeWidth-1)]=Terrain.START;terrain[Math.max(0,safeHeight-3)]![Math.max(0,safeWidth-3)]=Terrain.EXIT;return{schemaVersion:2,name:'Untitled Bobby Level',width:safeWidth,height:safeHeight,terrain,objects:[]};}
export function fromLevelMap(level:LevelMap,name='Bobby Level'):EditorLevel {const anchors=collapseObjectLayouts(level.objects);return normalizeEditorLevel({schemaVersion:2,name,width:level.width,height:level.height,terrain:level.terrain.map((row)=>[...row]),objects:anchors.map(({type,x,y})=>({type,x,y}))});}
/** Editor Draft -> pure semantic LevelMap. Runtime expansion remains Game.loadLevel's responsibility. */
export function toLevelMap(level:EditorLevel):LevelMap {const normalized=normalizeEditorLevel(level);return{width:normalized.width,height:normalized.height,terrain:normalized.terrain.map((row)=>[...row]),objects:normalized.objects.map(({type,x,y})=>({type,x,y}))};}
// Internal transitional aliases; Web public imports use the LevelMap names.
export const fromLevelData=fromLevelMap; export const toLevelData=toLevelMap;
export function normalizeEditorLevel(input:EditorLevel):EditorLevel {const width=clampDimension(Number(input.width)),height=clampDimension(Number(input.height));const terrain=Array.from({length:height},(_,y)=>Array.from({length:width},(_,x)=>normalizeTerrain(input.terrain?.[y]?.[x])));const occupied=new Set<string>(),objects:EditorObject[]=[];for(const raw of input.objects??[]){const x=Math.trunc(Number(raw.x)),y=Math.trunc(Number(raw.y)),type=normalizeObject(raw.type);if(type===ObjectId.EMPTY||isObjectLayoutPart(type))continue;if(x<0||y<0||x>=width||y>=height)continue;const cells=objectLayoutFor(type).cells.map((cell)=>({x:x+cell.dx,y:y+cell.dy}));if(cells.some((cell)=>cell.x<0||cell.y<0||cell.x>=width||cell.y>=height)||cells.some((cell)=>occupied.has(`${cell.x},${cell.y}`)))continue;for(const cell of cells)occupied.add(`${cell.x},${cell.y}`);objects.push({type,x,y});}const level:EditorLevel={schemaVersion:2,name:String(input.name||'Untitled Bobby Level').slice(0,120),width,height,terrain,objects};if(input.author)level.author=String(input.author).slice(0,80);if(input.description)level.description=String(input.description).slice(0,500);return level;}
export function validateEditorLevel(level:EditorLevel):LevelValidationIssue[]{const normalized=normalizeEditorLevel(level),issues:LevelValidationIssue[]=[];let starts=0,exits=0;for(const row of normalized.terrain)for(const type of row){if(type===Terrain.START)starts++;if(type===Terrain.EXIT)exits++;}if(starts===0)issues.push({level:'warning',message:'没有 Bobby 出生点；Engine 会使用第一个可步行格作为回退出生点。'});if(starts>1)issues.push({level:'warning',message:`存在 ${starts} 个出生点；原版语义只需要一个。`});if(exits===0)issues.push({level:'warning',message:'没有出口，因此地图通常无法正常通关。'});return issues;}
export function resizeEditorLevel(level:EditorLevel,width:number,height:number):EditorLevel{return normalizeEditorLevel({...level,width,height});}
export function serializeEditorLevel(level:EditorLevel):string{return`${JSON.stringify(normalizeEditorLevel(level),null,2)}\n`;}
export function parseEditorLevel(text:string):EditorLevel {const parsed=JSON.parse(text) as Partial<EditorLevel>;if(parsed.schemaVersion!==2)throw new Error(`不支持的地图 schemaVersion：${String(parsed.schemaVersion)}；当前只接受语义 schema v2`);if(!Array.isArray(parsed.terrain))throw new Error('JSON 缺少 terrain 二维数组');return normalizeEditorLevel(parsed as EditorLevel);}
function clampDimension(value:number):number{if(!Number.isFinite(value))return 16;return Math.min(128,Math.max(3,Math.trunc(value)));}
function normalizeTerrain(value:unknown):TerrainType{return typeof value==='string'&&value.length>0?value as TerrainType:Terrain.GROUND_C;}
function normalizeObject(value:unknown):ObjectType{return typeof value==='string'&&value.length>0?value as ObjectType:ObjectId.EMPTY;}
