import { FactRegistry, type FactDefinition } from "./FactRegistry.js";

/** 内置地图对象当前公开的语义标识；具体规则由消费 Fact 的机制解释。 */
export const builtinFactDefinitions: readonly FactDefinition[] = [
  { id: "bean-growth-space", description: "允许豆蔓生长的空间" },
  { id: "blocking", description: "标准通行需要检查的阻挡部位" },
  { id: "bonus-coin", description: "奖励金币目标" },
  { id: "carousel", description: "旋转木马对象" },
  { id: "climbable", description: "允许攀爬的部位" },
  { id: "cloud", description: "云对象" },
  { id: "cloud-space", description: "云可经过的空间" },
  { id: "collectible", description: "进入后可收集的对象" },
  { id: "crumbly-rock", description: "可被对应动作破坏的碎石" },
  { id: "dialog", description: "提供地图内对白的对象" },
  { id: "directional-passage", description: "按方向决定通行的部位" },
  { id: "dragon", description: "龙对象的整体语义" },
  { id: "dragon-trigger", description: "触发龙机关的部位" },
  { id: "egg-nest", description: "可接纳蛋的巢格" },
  { id: "exit", description: "关卡出口目标" },
  { id: "fence", description: "围栏部位" },
  { id: "filled-egg", description: "当前已填充的蛋目标" },
  { id: "flight-entry", description: "起飞入口" },
  { id: "flight-landing", description: "飞行着陆点" },
  { id: "forced-movement", description: "进入后产生连续移动的部位" },
  { id: "gate", description: "可开闭的门" },
  { id: "golden-carrot", description: "金胡萝卜奖励目标" },
  { id: "hazard", description: "可造成伤害的部位" },
  { id: "hidden-objective", description: "被覆盖的目标格" },
  { id: "interaction", description: "可触发对象交互的部位" },
  { id: "leaf", description: "叶片移动平台" },
  { id: "meltable", description: "可被融化的对象" },
  { id: "mirror", description: "镜子对象" },
  { id: "moving-platform", description: "可承载 Actor 的移动平台" },
  { id: "mowable", description: "可被割草机清除的部位" },
  { id: "mower", description: "割草机对象" },
  { id: "mower-conditional-overlay", description: "割草机专属覆盖层通行条件" },
  { id: "mower-parking", description: "割草机停靠位置" },
  { id: "pickup", description: "进入后领取道具的对象" },
  { id: "player", description: "ActorLifecycle 识别的可控角色" },
  { id: "portal", description: "传送门对象" },
  { id: "projectile", description: "投射物对象" },
  { id: "push-goal", description: "推箱目标格" },
  { id: "pushable", description: "可由推机制考虑的部位" },
  { id: "reach-all-players", description: "到达目标需所有玩家满足" },
  { id: "requires-unmounted-reach", description: "到达目标要求角色未骑乘" },
  { id: "ride-carried", description: "骑乘时随角色移动的对象" },
  { id: "rotatable", description: "可旋转的对象" },
  { id: "shovelable", description: "可用铲子清除的部位" },
  { id: "snow", description: "雪地对象" },
  { id: "stateful-block", description: "通行依赖当前状态的对象" },
  { id: "switch", description: "地图内开关对象" },
  { id: "terrain-overlay", description: "覆盖地形的部位" },
  { id: "timed-challenge", description: "地图内计时挑战对象" },
  { id: "vehicle", description: "可骑乘载具" },
  { id: "walkable", description: "标准通行可落脚的部位" },
  { id: "water", description: "水面部位" },
  { id: "waterfall", description: "瀑布部位" },
  { id: "windmill", description: "风车对象" },
];

export function createBuiltinFactRegistry(): FactRegistry {
  const registry = new FactRegistry();
  registry.registerAll(builtinFactDefinitions);
  return registry;
}
