import type { LevelMap } from '@bobby/model';
export interface LevelSource{edition:string;release?:string;releaseLabel?:string;packFile:string;packTitle?:string;packDescription?:string;levelIndex:number;decodedPath?:string;}
export interface DifficultyInfo{level:'tutorial'|'easy'|'medium'|'hard';source:'historical'|'estimated';label:string;collections?:string[];confidence?:number;}
export interface OfficialLevelData extends LevelMap{schemaVersion:2;id?:string;canonicalId?:string;publicId?:string;release?:string;chapter?:number;chapterTitle?:string;chapterLevel?:number;difficulty?:DifficultyInfo;source:LevelSource;sources?:LevelSource[];recordLength:number;recordSha256:string;dynamicSlots:number;terrainEncoding:'semantic-row-major';}
export interface CatalogLevel{id:string;canonicalId:string;publicId:string;number:number;release:string;releaseSourceId:string;releaseLabel:string;chapter:number;chapterTitle:string;chapterDescription:string;chapterLevel:number;recordSha256:string;width:number;height:number;dynamicSlots:number;objectCount:number;difficulty:DifficultyInfo;sources:LevelSource[];path:string;}
export interface CatalogChapter{id:string;release:string;releaseSourceId:string;releaseLabel:string;chapter:number;title:string;description:string;levelPublicIds:string[];}
export interface CatalogRelease{id:string;sourceId:string;order:number;label:string;中文名:string;levelCount:number;chapters:string[];}
export interface LevelCatalog{schemaVersion:number;totalSourceLevels:number;uniqueLevels:number;duplicateSourceRecords:number;primaryArt:{edition:string;tileSize:number;basePath:string};music:{basePath:string;format:string;files:string[]};releases:CatalogRelease[];chapters:CatalogChapter[];levels:CatalogLevel[];difficulty:{historicalNonTutorialLevels:number;estimatedLevels:number};}
export async function fetchJson<T>(url:string):Promise<T>{const response=await fetch(url);if(!response.ok)throw new Error(`Failed to fetch ${url}: ${response.status}`);return response.json() as Promise<T>;}
