import type { TinySynthAudioBackend } from './TinySynthAudio.js';
import { bindNavigation, escapeHtml, shell, type Navigate } from './common.js';
import { completedLevels, loadProfile } from './profile.js';
import { hasActiveLevelFilters, mountLevelFilters, randomFilteredLevel } from './level-filters.js';
import type { CatalogLevel, LevelCatalog } from './catalog.js';

export interface PageContext { app:HTMLDivElement;catalog:LevelCatalog;audio:TinySynthAudioBackend;navigate:Navigate; }
export function lastLevel(catalog:LevelCatalog):CatalogLevel{const stored=localStorage.getItem('bobby.lastLevel');if(stored){const found=catalog.levels.find((level)=>level.publicId===stored);if(found)return found;}return catalog.levels[0]!;}
export function preferredRelease(catalog:LevelCatalog):string{const saved=localStorage.getItem('bobby.selectedRelease');if(saved&&catalog.releases.some((release)=>release.id===saved))return saved;const stored=localStorage.getItem('bobby.lastLevel');return catalog.levels.find((level)=>level.publicId===stored)?.release??'base';}
function randomLevel(catalog:LevelCatalog):CatalogLevel{return catalog.levels[Math.floor(Math.random()*catalog.levels.length)]??catalog.levels[0]!;}
export function displayLevelId(level:CatalogLevel):string{return level.publicId.toUpperCase();}

export function renderHome(context:PageContext):void{const{app,catalog,audio,navigate}=context,last=lastLevel(catalog);audio.playMusic('title');app.innerHTML=shell(`<section class="hero"><div><div class="muted">BOBBY CARROT 5 · WEB REMASTER</div><h1>Bobby<br>Carrot</h1><p>保留第五代 Base + UP1～UP9 的原版高清美术、关卡结构和谜题机制，用现代浏览器重新实现 Camera、动画、键盘与手机操作。</p><div class="actions"><a class="primary-btn" href="play/${last.publicId}" data-nav>继续游玩 · ${displayLevelId(last)}</a><a class="ghost-btn" href="levels" data-nav>选择关卡</a><a class="ghost-btn" href="edit" data-nav>创建地图</a><button id="home-random" class="ghost-btn">随机一关</button></div></div><img class="hero-art" src="assets/art/hd/title.png" alt="Bobby Carrot 5 original title art" /></section><section class="stat-row"><div class="stat"><strong>10</strong><span>正式发行包</span></div><div class="stat"><strong>${catalog.uniqueLevels}</strong><span>唯一关卡</span></div><div class="stat"><strong>${completedLevels().size}</strong><span>已完成</span></div></section>`);bindNavigation(app,navigate);app.querySelector<HTMLButtonElement>('#home-random')?.addEventListener('click',()=>navigate(`/play/${randomLevel(catalog).publicId}`));}

export async function renderLevels(context:PageContext,releaseId:string,onRelease:(releaseId:string)=>void):Promise<void>{const{app,catalog,audio,navigate}=context;audio.playMusic('title');const last=lastLevel(catalog),release=catalog.releases.find((item)=>item.id===releaseId)??catalog.releases[0]!;localStorage.setItem('bobby.selectedRelease',release.id);const chapters=catalog.chapters.filter((chapter)=>chapter.release===release.id).sort((a,b)=>a.chapter-b.chapter),completed=completedLevels();app.innerHTML=shell(`<section class="level-browser-head"><div class="section-title"><div><h1>选择关卡</h1><p>按原版发行包 → 章节 → 关卡浏览。内部 001～485 编号不再作为玩家界面。</p></div></div><div class="level-browser-actions"><a class="primary-btn" href="play/${last.publicId}" data-nav>继续 · ${displayLevelId(last)}</a><button id="random-level" class="ghost-btn">随机一个关卡</button></div></section><div class="release-tabs" role="tablist" aria-label="Bobby Carrot 5 发行包">${catalog.releases.map((item)=>`<button class="release-tab ${item.id===release.id?'active':''}" data-release="${item.id}"><strong>${item.id==='base'?'BASE':item.id.toUpperCase()}</strong><span>${escapeHtml(item.中文名||item.label)}</span><small>${item.levelCount} 关</small></button>`).join('')}</div><section class="release-summary"><div><span class="eyebrow">${release.id==='base'?'BASE / FOREVER':release.id.toUpperCase()}</span><h2>${escapeHtml(release.中文名||release.label)}</h2></div><div class="muted">${chapters.length} 个章节 · ${release.levelCount} 关</div></section><div class="chapter-list">${chapters.map((chapter)=>renderChapter(catalog,chapter.id,completed)).join('')}</div><div class="difficulty-legend muted"><span><i class="difficulty-dot easy"></i>简单</span><span><i class="difficulty-dot medium"></i>中等</span><span><i class="difficulty-dot hard"></i>困难</span><span>带“≈”的是根据 A～F 历史难度合集估算；无“≈”为历史难度资料直接映射。</span></div>`);bindNavigation(app,navigate);app.querySelectorAll<HTMLButtonElement>('button[data-release]').forEach((button)=>button.addEventListener('click',()=>onRelease(button.dataset.release??'base')));await mountLevelFilters(catalog);app.querySelector<HTMLButtonElement>('#random-level')?.addEventListener('click',()=>{const chosen=hasActiveLevelFilters()?randomFilteredLevel(release.id):randomLevel(catalog);if(chosen)navigate(`/play/${chosen.publicId}`);});}

function renderChapter(catalog:LevelCatalog,chapterId:string,completed:Set<string>):string{const chapter=catalog.chapters.find((item)=>item.id===chapterId);if(!chapter)return'';const levels=chapter.levelPublicIds.map((publicId)=>catalog.levels.find((level)=>level.publicId===publicId)).filter((level):level is CatalogLevel=>Boolean(level));return`<section class="chapter-card"><header class="chapter-head"><div><div class="chapter-number">${chapter.chapter===0?'TUTORIAL':`CHAPTER ${chapter.chapter}`}</div><h3>${escapeHtml(chapter.title)}</h3></div><span class="muted">${levels.length} 关</span></header><div class="chapter-levels">${levels.map((level)=>{const done=completed.has(level.canonicalId);return`<a class="chapter-level ${done?'completed':''}" href="play/${level.publicId}" data-nav title="${escapeHtml(level.publicId)} · ${escapeHtml(level.difficulty.label)}"><span class="chapter-level-no">${level.chapterLevel}</span><span class="difficulty-badge ${level.difficulty.level} ${level.difficulty.source}">${escapeHtml(level.difficulty.label)}</span>${done?'<span class="done-mark" title="已通关">✓</span>':''}</a>`;}).join('')}</div></section>`;}

export function renderSettings(context:PageContext):void{const{app,audio,navigate}=context,profile=loadProfile();audio.playMusic('title');app.innerHTML=shell(`<div class="section-title"><h1>设置</h1><p>保留原始 MIDI；TinySynth 可切换两套算法音色。SoundFont 后端会作为独立实现接入。</p></div><section class="profile-strip"><div><strong>${profile.bonusCoins}</strong><span>Bonus Coin</span></div><div><strong>${profile.goldenCarrots}</strong><span>Golden Carrot</span></div><div><strong>${profile.superKey?'已获得':'未获得'}</strong><span>Super Key</span></div></section><section class="settings-card"><div class="setting"><div><strong>音乐</strong><div class="muted">WebAudio TinySynth 1.1.3 · 原始 .mid</div></div><label class="switch-label"><input id="music-enabled" type="checkbox" ${audio.isEnabled()?'checked':''}> 启用</label></div><div class="setting"><div><strong>MIDI 音色</strong><div class="muted">FM 更接近 GM；Chip 更接近简单硬件合成</div></div><select id="midi-tone"><option value="fm" ${audio.getTone()==='fm'?'selected':''}>TinySynth FM</option><option value="chip" ${audio.getTone()==='chip'?'selected':''}>TinySynth Chip</option></select></div><div class="setting"><div><strong>混响</strong><div class="muted">减少干硬/尖锐感</div></div><input id="midi-reverb" type="range" min="0" max="100" value="${Math.round(audio.getReverbLevel()*100)}"></div><div class="setting"><div><strong>音乐音量</strong><div class="muted">0–100%</div></div><input id="music-volume" type="range" min="0" max="100" value="${Math.round(audio.getMusicVolume()*100)}"></div><div class="setting"><div><strong>音效音量</strong><div class="muted">收集/机关反馈</div></div><input id="sound-volume" type="range" min="0" max="100" value="${Math.round(audio.getSoundVolume()*100)}"></div><div class="setting"><div><strong>SoundFont MIDI</strong><div class="muted">下一后端：SpessaSynth + 可再分发 SF2/SF3；不替换原 MIDI</div></div><span>Planned</span></div><div class="setting"><div><strong>操作</strong><div class="muted">WASD / 方向键 / Drag / Wheel / Pinch / ~ DEBUG</div></div><span>Modern</span></div></section>`);bindNavigation(app,navigate);app.querySelector<HTMLInputElement>('#music-enabled')?.addEventListener('change',(event)=>audio.setEnabled((event.currentTarget as HTMLInputElement).checked));app.querySelector<HTMLInputElement>('#music-volume')?.addEventListener('input',(event)=>audio.setMusicVolume(Number((event.currentTarget as HTMLInputElement).value)/100));app.querySelector<HTMLInputElement>('#sound-volume')?.addEventListener('input',(event)=>audio.setSoundVolume(Number((event.currentTarget as HTMLInputElement).value)/100));app.querySelector<HTMLSelectElement>('#midi-tone')?.addEventListener('change',(event)=>audio.setTone((event.currentTarget as HTMLSelectElement).value==='chip'?'chip':'fm'));app.querySelector<HTMLInputElement>('#midi-reverb')?.addEventListener('input',(event)=>audio.setReverbLevel(Number((event.currentTarget as HTMLInputElement).value)/100));}
